# Generated by Django 6.0.2 on 2026-03-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mobile_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
