# Generated by Django 6.0.2 on 2026-03-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_mobile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mobile_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
