# Generated by Django 6.0.2 on 2026-04-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imei_number',
            field=models.CharField(max_length=20),
        ),
    ]
