# Generated by Django 6.0.2 on 2026-04-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
